### ISSUE TITLE
onChange or onClick in Timepicker

### ISSUE THREAD

**Issue by nitinsonawane234** [kartik-v/yii2-widgets#380]
Is there is any ways to achieve onChange or onClick events in kartik timepicker ?

**Comment by thadudexx** [comment]
Did you try update?

```
pluginEvents = [
    "show" => "function(e) {  # `e` here contains the extra attributes }",
    "hide" => "function(e) {  # `e` here contains the extra attributes }",
    "update" => "function(e) {  # `e` here contains the extra attributes }",
];
```

**Comment by nitinsonawane234** [comment]
> Did you try update?
> 
> ```
> pluginEvents = [
>     "show" => "function(e) {  # `e` here contains the extra attributes }",
>     "hide" => "function(e) {  # `e` here contains the extra attributes }",
>     "update" => "function(e) {  # `e` here contains the extra attributes }",
> ];
> ```

Exception (Unknown Property) &#039;yii\base\UnknownPropertyException&#039; with message &#039;Setting unknown property: kartik\widgets\TimePicker::pluginEvents &#039; 

in D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Component.php:209

Stack trace:
#0 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\BaseYii.php(546): yii\base\Component-&gt;__set(&#039;pluginEvents &#039;, Array)
#1 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\BaseObject.php(107): yii\BaseYii::configure(Object(kartik\widgets\TimePicker), Array)
#2 [internal function]: yii\base\BaseObject-&gt;__construct(Array)
#3 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass-&gt;newInstanceArgs(Array)
#4 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container-&gt;build(&#039;kartik\\widgets\\...&#039;, Array, Array)
#5 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container-&gt;get(&#039;kartik\\widgets\\...&#039;, Array, Array)
#6 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Widget.php(137): yii\BaseYii::createObject(Array)
#7 D:\Xampp\htdocs\gccvatpro_adv\backend\views\tax-category\_form.php(79): yii\base\Widget::widget(Array)
#8 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\View.php(336): require(&#039;D:\\Xampp\\htdocs...&#039;)
#9 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\View.php(254): yii\base\View-&gt;renderPhpFile(&#039;D:\\Xampp\\htdocs...&#039;, Array)
#10 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\View.php(156): yii\base\View-&gt;renderFile(&#039;D:\\Xampp\\htdocs...&#039;, Array, NULL)
#11 D:\Xampp\htdocs\gccvatpro_adv\backend\views\tax-category\update.php(14): yii\base\View-&gt;render(&#039;_form&#039;, Array)
#12 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\View.php(336): require(&#039;D:\\Xampp\\htdocs...&#039;)
#13 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\View.php(254): yii\base\View-&gt;renderPhpFile(&#039;D:\\Xampp\\htdocs...&#039;, Array)
#14 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\web\View.php(212): yii\base\View-&gt;renderFile(&#039;D:\\Xampp\\htdocs...&#039;, Array, Object(backend\controllers\TaxCategoryController))
#15 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\web\Controller.php(49): yii\web\View-&gt;renderAjax(&#039;update&#039;, Array, Object(backend\controllers\TaxCategoryController))
#16 D:\Xampp\htdocs\gccvatpro_adv\backend\controllers\TaxCategoryController.php(417): yii\web\Controller-&gt;renderAjax(&#039;update&#039;, Array)
#17 [internal function]: backend\controllers\TaxCategoryController-&gt;actionUpdate(&#039;2007&#039;, &#039;US&#039;, &#039;NA&#039;, &#039;NA&#039;)
#18 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#19 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction-&gt;runWithParams(Array)
#20 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller-&gt;runAction(&#039;update&#039;, Array)
#21 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module-&gt;runAction(&#039;tax-category/up...&#039;, Array)
#22 D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application-&gt;handleRequest(Object(yii\web\Request))
#23 D:\Xampp\htdocs\gccvatpro_adv\index.php(33): yii\base\Application-&gt;run()
#24 {main}

**Comment by nitinsonawane234** [comment]
> Did you try update?
> 
> ```
> pluginEvents = [
>     "show" => "function(e) {  # `e` here contains the extra attributes }",
>     "hide" => "function(e) {  # `e` here contains the extra attributes }",
>     "update" => "function(e) {  # `e` here contains the extra attributes }",
> ];
> ```

Exception (Unknown Property) &#039;yii\base\UnknownPropertyException&#039; with message &#039;Setting unknown property: kartik\widgets\TimePicker::pluginEvents &#039; 
in D:\Xampp\htdocs\gccvatpro_adv\vendor\yiisoft\yii2\base\Component.php:209

**Comment by nitinsonawane234** [comment]
> Did you try update?
> 
> ```
> pluginEvents = [
>     "show" => "function(e) {  # `e` here contains the extra attributes }",
>     "hide" => "function(e) {  # `e` here contains the extra attributes }",
>     "update" => "function(e) {  # `e` here contains the extra attributes }",
> ];
> ```

Exception (Unknown Property) &#039;yii\base\UnknownPropertyException&#039; with message &#039;Setting unknown property: kartik\widgets\TimePicker::pluginEvents &#039; 
in D:\Xampp\htdocs\adv\vendor\yiisoft\yii2\base\Component.php:209
